sudo: required

language: node_js
node_js:
  - "lts/*"
go:
  - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_$HUGO_VERSION_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install

before_script:
  - npm install -g gulp-cli

script:
  - gulp

#deploy:
#  provider: script
#  local-dir: public
#  target-branch: master
#  skip-cleanup: true
#  on:
#    branch: source

env:
  - PRODUCTION=true
  - HUGO_VERSION="0.37"

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
